### ISSUE TITLE
MIDI Event resolution, tempo, and PPQ

### ISSUE THREAD

**Issue by ChemiCalChems** [wintergatan-community/vmmx-schema#3]
The following is a discussion about what the resolution for MIDI events should be in our output files.

MIDI uses two numbers to define the resolution of events it can store in files. 

- BPM: Beats Per Minute, which is variable, and can be changed during the song by sending a tempo meta event. 

- PPQ(N): Pulses per quarter (note). This is stored in the header of the MIDI file, and thus is a constant to that file. As the name implies, it specifies the amount of ticks between each quarter note, and ultimately defines the resolution of MIDI clock ticks, and events.

The MIDI beat clock runs at 24 PPQ, so that's the minimum PPQ for event storage in files. However, more modern hardware chooses to divide each tick of the beat clock into 20 ticks, thus getting an effective PPQ count of 480 = 24x20. 960 PPQ is used in some occassions. 

Is there a primary reason not to use a higher PPQ? Are files bigger?

Files with a higher PPQ don't end up being bigger if they have the same number of MIDI events (note on, note off, meta events, etc...), because MIDI stores timing through deltas between events, that is, MIDI doesn't care about absolute time, just counts clock ticks until the next event has to be played. It is therefore advisable, at least in principle, if your software and hardware can handle it, to use a higher PPQ, as more resolution in MIDI events is able to store the playback information more accurately.

Since PPQ stores pulses per beat, however, this means the resolution of time events is tempo dependant. The difference in microseconds between two ticks is 60x1,000,000/(BPMxPPQ). In milliseconds, this expression is 60x1,000/(BPMxPPQ). The proof for these expressions is left as an exercise to the reader (I study physics, do you really want me not to put this in somewhere?). 

It is thus advisable to have an idea of the lowest tempo the end user will want to use, to have a decent event resolution at those slow tempos. The problem is inexistent at higher tempos, as there would be more ticks per unit time.

An example: at 120 BPM 24 PPQ, ticks are separated by 20.83ms, but at 60BPM 24PPQ that difference goes up to 41ms. 

Is this a problem, though? It depends on what one wants to store. In our case, events on the programming wheel are eighth notes, sixteenth notes and eighth note triplets. These events don't really care about absolute time, just timing relative to the tempo, and that is why PPQ is a useful way to store these things. In our case, we would need to store 

- half quarter notes = eighth notes, PPQ must be a multiple of 2
- quarter quarter notes = sixteenth notes, PPQ must be a multiple of 4
- thirds of a quarter note = eighth note triplets = PPQ must be a multiple of 3.

So our minimum PPQ to accurately store programming wheel events is 12. This example also illustrates why having PPQ values divisible by 3 is useful, as it allows to store triplets. In fact, a PPQ value of 12 even allows the storage sixteenth note triplets. 

This, however, is not good enough for events that do depend on absolute time. We have been discussing events like hammer-ons and pull-offs from the bass, for example. A human playing at 120 BPM can do as many pull-offs and hammer-ons per second as a human playing at 60 BPM, because the human doesn't give a damn about tempo, but MIDI would have a hard time storing events like those at a lower tempo. Solution to this problem? Even though we don't need a higher PPQ than 12 (24 to fit the MIDI standard) for programming wheel events, we do need it for these tempo-agnostic events. 

The discussion about PPQ, thus, turns to finding out how quick a human can perform hammer-ons, pull-offs, and other events. I think not even a very well trained teenager can move their hand repeatedly quicker than 50ms up 50ms down, and if they can, I doubt it's for musical purposes, as it's rather useless to do so on a bass, let's be honest. Especially at low tempo, since at high tempo, where things go quick, we already have more clock resolution. Imagine a slow 60 BPM balad, and Steve Vai shredding over it at 20 notes per second.

On the other hand, one must decide what's the lowest tempo one would be performing these insane events at. Let's say Steve Vai *does* want to shred at 60 BPM at 20 notes per second, as a safe compromise.

That would mean we would need a 50ms tick at 60 BPM, or a PPQ value of 20. Manageable? Yes! Let's find a good highly divisible number slightly above 20. Uhmm... 24.

There is a reason, I guess, why 24 PPQ was set as the minimum standard for MIDI. However, another problem pops up, quantization. Steve Vai can now shred at 20 notes per second at 60 BPM, but can he shred at 20 notes per second on the "offbeat", i.e., every note is between two ticks? Well, he can, but his insane solo will be quantized wrong. So, in the end we do need more resolution. How much more? I'm not sure now. The rest of problems were rather easy to solve analytically, or by setting ridiculous examples of heavy metal guitarrists, this is more opinion based.

How far down do we want to quantize notes? Is 50ms at 60BPM good enough? Maybe we would want 20ms? Maybe 5? I'd say 5ms is good enough, in my personal opinion, because you can't tell a 5ms difference between events reliably anymore. At 60BPM, that'd be 200 PPQ, or again, looking for a nicely divisible number, we could go with 240 PPQ. 

This 240 PPQ value (2^4 x 3 x 5) would allow us to store
- All the way down to 64th notes
- All the way down to 128th note triplets
- Divisible by 5, so quintuplets would even be a thing
- Quantization down to a bit lower than 5ms
- Same file size as 24PPQ, 10 times as much resolution.

Why not go to the moon at 960 PPQ? Unsure, we could do it, but is it useful and do we have a reliable clock in a web browser to handle 960 PPQ at 180 BPM or 0.3ms ticks? Maybe, but I'm staying on the safe side. 1.2ms ticks (240 PPQ 180 BPM) is good enough to ask for a clock.

I thus recommend a PPQ value of 240, or 120 on the low side, 480 on the high side for our files, but I believe 240'll do.

EDIT: I forgot to add, there is also a completely different timing scheme based on actually absolute time (both timings explain in detail [here](http://www.harfesoft.de/aixphysik/sound/midi/pages/miditmcn.html) ) but that's a whole other discussion, and relative time is what has been used forever. Absolute time is more used to sincronize various MIDI devices together on a network and stuff like that, not our usage case.

**Comment by iansedano** [comment]
Great write up, thanks! Agree that 240 sounds like a good compromise. I wonder what PPQ values Tone.js uses/can use.

Another thing in favor of higher PPQ (around 1ms resolution) is the concept of "swing" - for those that aren't familiar with the idea, is that musicians almost always play with some "swing" and this is why there is a noticeable difference between an electronic sequencer that plays "on the grid" and a human player. The human player drags behind the beat or anticipates it, and it varies. An easily appreciable example of swing is the typical "shuffle" that has many variations in jazz and blues. 

Of course, the MMX is no human player, but since the MMX will be using stud welded plates, there will likely be the possibility of programmed swing, a common feature in drum machines and other sequencers.

There are also producers who like to offset their notes randomly a few ms to the left or right because it sounds better to them. While I don't believe people can reliably tell the difference between an isolated event 1ms and 2ms late, overall I believe you can perceive these small temporal differences in the context of a song or groove.

**Comment by ChemiCalChems** [comment]
@iansedano Tone.js shouldn't care too much about what the PPQ is, I don't think. And indeed, you can't quantize swing with a low PPQ, but 240 PPQ means you are able to swing as little as 1/240 of a quarter note and still have it be recorded properly.

This also applies to small temporal differences. Our max tick size will be less than 5ms at 60 BPM, going down as the tempo goes up. So I think it's a good compromise.

My point is 1ms is tiny timewise. 5ms is still tiny, and that's going to be our max tick if we go for 240 PPQ.

**Comment by ollpu** [comment]
The tone.js format is quite well described in the [readme](https://github.com/Tonejs/Midi/blob/master/README.md#format), and it seems to include a PPQ field. Timestamps are stored in absolute ticks (plus a redundant seconds-field).
(I also noticed that CC's are floats in the range 0-1, which is a little unfortunate.)

*This was written under the assumption that MIDI BPM in Tone.js is constant throughout the file:*
In addition to deciding PPQ, we also have to decide the arbitrary value of BPM. Tempo is irrelevant in programming pin data as the actual rate played at will vary. Similarly, tempo is irrelevant in performance data because the underlying tempo of the machine doing it's thing varies. So: PPQ determines programming resolution, while BPM (multiplied by PPQ) determines performance data resolution (assuming we stick to real-time correspondence there).

Edit: Looks like the readme isn't really comprehensive. More investigation needed.

**Comment by ChemiCalChems** [comment]
@ollpu I tend to disagree about tempo being irrelevant. There is a speed at which the song should be played according to the author. Simple as that.

**Comment by mozi-h** [comment]
I guess we'll roll with 240?
React 👍 or 👎

**Comment by mozi-h** [comment]
Let's keep it at 240. People can make an issue / PR if they REALLY hate it
